// ═══════════════════════════════════════════════════════════════════
// Services Index — Re-exports all services
// ═══════════════════════════════════════════════════════════════════

export { default as api } from './api'
export { authService } from './auth.service'
export { productService, type ProductFilters, type ProductFormData, type ProductVariantFormData } from './product.service'
export { categoryService, type CategoryFilters, type CategoryFormData } from './category.service'
export { orderService, type OrderFilters, type OrderStatusUpdate } from './order.service'
export { vendorService, type VendorFilters, type VendorFormData } from './vendor.service'
export { customerService, type CustomerFilters, type CustomerStats } from './customer.service'
export { settingsService } from './settings.service'
export { attributeTemplateService, vendorTemplateService } from './attribute-template.service'
export { reviewService, type ReviewFilters, type ReviewStats } from './review.service'
export { couponService, type CouponFilters, type CouponStats, type ValidateCouponRequest, type ValidateCouponResponse } from './coupon.service'
export { flashSaleService, type FlashSaleFilters, type FlashSaleStats } from './flash-sale.service'
export { bannerService, type BannerFilters, type BannerPositionInfo } from './banner.service'
export { newsletterService, type SubscriberFilters, type NewsletterStats } from './newsletter.service'
export { analyticsService, type DateRange, type SalesReport, type VendorReport, type ProductReport } from './analytics.service'
export type { ExportFilters, ExportStatus, ImportResult } from '@/types'
export { payoutService, type PayoutFilters, type PayoutStats, type BankAccount, type CreateBankAccountRequest } from './payout.service'
export { uploadService, type UploadedFile, type UploadProgress, type UploadOptions, type ChunkedUploadSession } from './upload.service'
export { notificationService, type NotificationFilters } from './notification.service'
export { shippingService } from './shipping.service'
export { healthService } from './health.service'
export { activityService } from './activity.service'
export { inventoryService } from './inventory.service'
export { paymentService, refundService, webhookService } from './payment.service'
export { pageService, faqService, blogService, contactService } from './cms.service'
export { backupService, type BackupFile, type BackupStats, type BackupHealth, type BackupListResponse } from './backup.service'
